export const serviceAreas = [
  {
    shire: "Buckinghamshire",
    towns: [
      "Amersham",
      "Aylesbury",
      "Beaconsfield",
      "Bourne End",
      "Buckingham",
      "Burnham",
      "Chalfont St Giles",
      "Chalfont St Peter",
      "Chesham",
      "Denham",
      "Flackwell Heath",
      "Gerrards Cross",
      "Great Missenden",
      "Haddenham",
      "Hazlemere",
      "High Wycombe",
      "Iver",
      "Little Chalfont",
      "Marlow",
      "Milton Keynes",
      "Newport Pagnell",
      "Olney",
      "Prestwood",
      "Princes Risborough",
      "Stokenchurch",
      "Wendover",
      "Winslow",
      "Wooburn",
    ],
  },
  {
    shire: "Greater London",
    towns: [
      "Barking and Dagenham",
      "Barnet",
      "Bexley",
      "Brent",
      "Bromley",
      "Camden",
      "City of London",
      "Croydon",
      "Ealing",
      "Enfield",
      "Greenwich",
      "Hackney",
      "Hammersmith and Fulham",
      "Haringey",
      "Harrow",
      "Havering",
      "Hillingdon",
      "Hounslow",
      "Islington",
      "Kensington and Chelsea",
      "Kingston upon Thames",
      "Lambeth",
      "Lewisham",
      "Merton",
      "Newham",
      "Redbridge",
      "Richmond upon Thames",
      "Southwark",
      "Sutton",
      "Tower Hamlets",
      "Waltham Forest",
      "Wandsworth",
      "Westminster",
    ],
  },
  {
    shire: "Oxfordshire",
    towns: [
      "Abingdon-on-Thames",
      "Banbury",
      "Bicester",
      "Burford",
      "Carterton",
      "Charlbury",
      "Chipping Norton",
      "Didcot",
      "Faringdon",
      "Henley-on-Thames",
      "Kidlington",
      "Oxford",
      "Thame",
      "Wallingford",
      "Wantage",
      "Watlington",
      "Witney",
      "Woodstock",
    ],
  },
  {
    shire: "Hertfordshire",
    towns: [
      "Abbots Langley",
      "Baldock",
      "Berkhamsted",
      "Bishop's Stortford",
      "Borehamwood",
      "Buntingford",
      "Bushey",
      "Cheshunt",
      "Chorleywood",
      "Harpenden",
      "Hatfield",
      "Hemel Hempstead",
      "Hertford",
      "Hitchin",
      "Hoddesdon",
      "Kings Langley",
      "Letchworth Garden City",
      "Potters Bar",
      "Radlett",
      "Rickmansworth",
      "Royston",
      "St Albans",
      "Sawbridgeworth",
      "Stevenage",
      "Tring",
      "Ware",
      "Watford",
      "Welwyn Garden City",
    ],
  },
  {
    shire: "Berkshire",
    towns: [
      "Ascot",
      "Bracknell",
      "Crowthorne",
      "Hungerford",
      "Maidenhead",
      "Newbury",
      "Pangbourne",
      "Reading",
      "Sandhurst",
      "Slough",
      "Thatcham",
      "Twyford",
      "Windsor",
      "Wokingham",
      "Woodley",
    ],
  },
  {
    shire: "Bedfordshire",
    towns: [
      "Ampthill",
      "Arlesey",
      "Bedford",
      "Biggleswade",
      "Dunstable",
      "Flitwick",
      "Houghton Regis",
      "Kempston",
      "Leighton Buzzard",
      "Luton",
      "Potton",
      "Sandy",
      "Shefford",
      "Stotfold",
      "Woburn",
    ],
  },
  {
    shire: "Northamptonshire",
    towns: [
      "Brackley",
      "Burton Latimer",
      "Corby",
      "Daventry",
      "Desborough",
      "Higham Ferrers",
      "Irthlingborough",
      "Kettering",
      "Northampton",
      "Oundle",
      "Raunds",
      "Rothwell",
      "Rushden",
      "Thrapston",
      "Towcester",
      "Wellingborough",
    ],
  },
] as const;

export const surroundingShires =
  "Oxfordshire, Hertfordshire, Berkshire, Bedfordshire and Northamptonshire";

export const surroundingAreaSentence = `People come from across Buckinghamshire, from Greater London, and from the surrounding shires: ${surroundingShires}.`;

export const buckinghamshireAnswer = `Yes. ${surroundingAreaSentence} They come to the garden room in Little Hampden or meet outdoors nearby. If the journey is too far, we can meet online.`;

export const areaServed = [
  { "@type": "Place" as const, name: "The Chilterns" },
  ...serviceAreas.flatMap((area) => [
    { "@type": "AdministrativeArea" as const, name: area.shire },
    ...area.towns.map((name) => ({ "@type": "City" as const, name })),
  ]),
];
