import { buildGuideBody } from "@/content/seo/build-guide";
import type { SeoGuideContent } from "@/lib/seo-types";

export const howToImproveLandingPageConversionsContent: SeoGuideContent = buildGuideBody({
  valueBenefits: [
    {
      title: "Hero proof",
      outcome: "Lift conversions above the fold.",
      detail:
        "Add a publishable editorial quote so visitors see third-party validation before they scroll.",
      accent: "#3B82F6",
    },
    {
      title: "Clickable verification",
      outcome: "Let skeptics self-serve trust.",
      detail:
        "Badge links to a full review profile—reducing support chats and bounce rate.",
      accent: "#D4A943",
    },
    {
      title: "Consistent CTA story",
      outcome: "Align copy with what was reviewed.",
      detail:
        "Your profile summary reinforces claims on the landing page, improving message match.",
      accent: "#22C55E",
    },
  ],
  winningParagraphs: [
    "Landing page conversion is the percentage of visitors who take your desired action—signup, trial, demo or purchase. Winning means improving that rate without simply buying more traffic.",
    "Measure one primary CTA per page. Multiple competing buttons dilute focus and confuse analytics.",
    "Conversion optimisation combines clarity, speed, proof and offer fit. Skip any pillar and tests underperform.",
    "Benchmark mobile and desktop conversion separately—fixes on one often do not transfer.",
    "Log heatmaps on pricing pages during campaign weeks to see if proof is actually seen.",
    "Treat conversion as a weekly metric, not a launch-week panic—small proof and copy fixes compound when traffic is steady.",
    "A landing page that converts earns the right to more traffic—fix belief before you scale spend.",
  ],
  trustParagraphs: [
    "Visitors scan for risk before value. If proof is missing, they never read your brilliant feature list.",
    "UK audiences respond to straightforward copy and external validation—not superlatives without evidence.",
    "A conversion lift from proof is often the cheapest win because it improves every traffic source at once.",
    "Proof reduces cognitive load: visitors spend less energy deciding if you are real and more evaluating fit.",
    "A/B tests on headlines fail when underlying trust is weak—fix proof first, then test copy.",
  ],
  playbookParagraphs: [
    "Clarify the headline: who it is for, outcome delivered, timeframe if relevant. Jargon headlines kill conversion.",
    "Support the headline with one subhead and a single primary CTA. Repeat CTA after major sections.",
    "Use real product visuals above the fold. Show the interface solving the problem, not abstract icons.",
    "Cut form fields to the minimum viable data. Every extra field costs completions.",
    "Match ad or email copy to the landing page verbatim where possible. Message mismatch is a silent killer.",
    "Add social proof in the first screen: quote, logo row or review badge with link to full profile.",
    "Address top three objections inline: pricing, setup time, data security—whatever analytics show.",
    "Improve load speed: compress images, lazy-load below-fold media, avoid heavy scripts on mobile.",
    "Test CTA copy that describes the next step: “Start free trial” beats “Submit”.",
    "Use directional cues—arrows, contrast—to draw eyes to the CTA without clownish design.",
    "Remove navigation clutter on paid landing pages. Fewer exits mean more conversions.",
    "Embed Review Signal quote and badge linking to the live profile—give skeptics proof in one click.",
    "Record session replays on high-traffic pages monthly—watch where cursors hesitate and forms abandon.",
    "Test social proof placement before versus after feature grids; order matters more than volume of proof.",
    "Align ad keywords with headline nouns; mismatch is a common hidden conversion leak.",
    "Add a secondary CTA for visitors not ready to buy—newsletter, demo or checklist keeps the relationship warm.",
    "Snapshot conversion rate before and after adding your review quote so you know proof impact.",
    "Document headline and proof tests in one place—teams that log experiments repeat wins instead of guessing each campaign.",
    "Share your profile link in retargeting ads with “independently reviewed” copy so warm visitors see verification before they return.",
    "Prune thin landing variants quarterly; fewer pages with stronger proof often beat a sprawl of untested URLs.",
    "After each release, confirm the live page still matches what your editorial profile describes.",
    "Pitch partners for co-branded landing tests only when your page already converts organic traffic with proof above the fold.",
    "Weekly, export conversion by landing URL and fix the worst performer first—usually proof or headline mismatch, not traffic quality.",
    "Use scroll-depth events to confirm visitors see your quote; if not, move proof higher before testing button colour.",
    "Record five-second user tests on mobile—ask what the page sells and whether they would click; fix confusion before CTA tests.",
    "Align hero imagery with ad creative so paid visitors feel continuity, not bait-and-switch.",
    "Reduce hero text to one promise and one proof line—dense paragraphs rarely convert cold traffic.",
    "Add a micro-FAQ accordion under the CTA with three objections from sales—expand only if analytics show scroll.",
  ],
  sellParagraphs: [
    "Review Signal gives landing pages a conversion-focused proof stack: publishable quote, verification badge and public profile URL.",
    "Implement in an afternoon after publication—no dev project required for basic placement.",
    "Choose Starter (£99) for lean pages or Enhanced (£199) when you need richer editorial detail near complex offers.",
    "Study /example-review to mirror quote length and badge placement on your highest-traffic campaign page.",
  ],
  convertParagraphs: [
    "Conversion rate optimisation without proof optimises the wrong thing. Add verification, then test headlines and layouts.",
    "Place the editorial quote directly under the hero CTA so it reinforces the click visitors are about to make.",
    "Review the example profile to see how concise summaries support fast landing page comprehension.",
    "On paid landing pages, hide nav but keep the badge visible—proof should not disappear when you remove distractions.",
    "If form abandonment spikes on mobile, move the profile link above the fold; thumbs should not scroll three screens for trust.",
  ],
  credibleParagraphs: [
    "Generic trust seals do little on modern landing pages. Visitors click through to evidence or ignore them.",
    "Editorial review profiles provide a substantive destination behind your badge—real copy, review ID, reviewed signals.",
    "Link to guidelines when visitors ask how reviews work; transparency supports conversion on high-consideration products.",
    "Log the date you added editorial proof on the page—when conversion lifts, you will know which change mattered.",
    "Do not paraphrase the publishable quote beyond recognition; attribution and accuracy keep the proof credible.",
    "Pair the quote with a single customer metric you can defend—specificity on landing pages beats vague social proof.",
  ],
  sellBullets: [
    "Short editorial quote formatted for hero placement",
    "Badge linking to verifiable profile and review ID",
    "Summary aligned with landing page claims",
    "Profile URL for retargeting and email match-back",
    "Backlink from profile to your primary site",
    "Directory discovery for supplemental traffic",
  ],
  placementParagraphs: [
    "Test proof placement with the same discipline you test headlines.",
    "Run one A/B test: hero quote only versus hero quote plus badge—measure CTA clicks, not vanity scroll depth.",
    "On long sales pages, repeat the profile link after the objection-handling section where visitors pause longest.",
  ],
  placementBullets: [
    "Directly under hero CTA",
    "Beside lead capture forms",
    "Sticky bar on long sales pages",
    "Pricing section sidebar",
    "Mobile: collapse to badge + link",
    "Thank-you page reinforcing decision",
  ],
  comparisonParagraphs: [
    "Teams often run endless headline tests while leaving the hero without verifiable proof—conversion stalls because visitors still doubt the vendor.",
    "Review Signal gives landing pages a linked editorial record, so the first screen shows evidence visitors can open before they click your CTA.",
    "Conversion tools optimise clicks; editorial proof reduces the doubt that makes clicks worthless—fix belief before button colour.",
    "Visitors who open your profile and return to the page are your best A/B test segment—study what they do next on the page.",
  ],
  fastWinsParagraphs: [
    "This week, add quote and badge under the hero CTA and remove one form field—measure completion rate for seven days.",
    "Match your ad headline to the landing H1 word-for-word before spending more on traffic.",
    "Export last month’s landing page conversion rate and set a single proof-related goal for the next sprint.",
  ],
  nextStepsParagraphs: [
    "Apply at /submit with the landing URL you will promote, compare Starter (£99) and Enhanced (£199) on /pricing, and copy structure ideas from /example-review.",
    "After publication, deploy proof on your highest-spend campaign page first— that is where conversion gains pay back fastest.",
    "Tag profile links in ads and email UTMs so you can attribute conversions to proof-driven visits versus generic homepage traffic.",
    "Re-test your highest-traffic landing page thirty days after adding proof—compare CTA clicks, not only headline CTR from ads.",
  ],
  winsBullets: [
    "Single primary CTA per page",
    "Add quote + badge to hero",
    "Cut one form field",
    "Improve mobile load time",
    "Rewrite headline for clarity",
    "Log top three objections from sales",
    "Apply for Review Signal profile",
    "Run one A/B test on CTA copy",
  ],
  faq: [
    {
      q: "How can I improve landing page conversion rate?",
      a: "Clarify the offer, speed up mobile, reduce form friction and add verifiable proof above the fold. Test one change at a time. Editorial review quotes and profile links help skeptical visitors convert.",
    },
    {
      q: "What is a good conversion rate for SaaS landing pages?",
      a: "Rates vary by traffic quality and offer. Focus on relative improvement from your baseline. Proof and clarity often beat industry benchmarks as goals.",
    },
    {
      q: "Where should social proof go on a landing page?",
      a: "In the first screenful near the CTA. Link to a full independent review profile for visitors who want depth.",
    },
    {
      q: "Does a review badge help landing pages?",
      a: "Yes—when it links to a real editorial profile. Visitors verify, then return to convert with more confidence.",
    },
    {
      q: "Can I A/B test Review Signal placement?",
      a: "Absolutely—test hero vs mid-page placement. Keep the profile URL consistent so results are measurable.",
    },
    {
      q: "What copy can I use from my review?",
      a: "Use the publishable quote with Review Signal attribution. Do not alter meaning; link to the profile for full context.",
    },
    {
      q: "How much does proof cost?",
      a: "Starter profiles from £99, Enhanced from £199, covering manual review and published assets if accepted.",
    },
    {
      q: "Should landing pages have navigation?",
      a: "Paid campaign pages often convert better with minimal nav. Organic pages may keep nav—prioritise proof either way.",
    },
  ],
});
