import { buildGuideBody } from "@/content/seo/build-guide";
import type { SeoGuideContent } from "@/lib/seo-types";

export const howToGetBacklinksForYourStartupContent: SeoGuideContent = buildGuideBody({
  valueBenefits: [
    {
      title: "Citeable profile page",
      outcome: "Give partners a page worth linking to.",
      detail:
        "Your Review Signal profile is a real editorial URL—not a thin affiliate doorway.",
      accent: "#3B82F6",
    },
    {
      title: "Directory presence",
      outcome: "Pick up structured discovery links.",
      detail:
        "Published products can appear in the Review Signal directory alongside other reviewed tools.",
      accent: "#D4A943",
    },
    {
      title: "Outbound to your site",
      outcome: "Turn profile readers into visitors.",
      detail:
        "Profiles link back to your website so referral traffic follows citation value.",
      accent: "#22C55E",
    },
  ],
  winningParagraphs: [
    "Backlinks remain a core SEO signal: other sites pointing to yours. For UK startups, winning means earning links from relevant, reputable pages—not buying bulk links that risk penalties.",
    "Think in assets worth citing: original research, tools, definitive guides and verifiable review profiles journalists can reference.",
    "Quality beats quantity. One link from a respected industry publication outweighs dozens from irrelevant directories.",
    "Prioritise relevance over domain score—a niche newsletter beats an unrelated high-authority page.",
    "Batch outreach after publishing citeable research so you pitch once with momentum.",
    "Links from real relationships outlast links from bulk outreach—invest in helpful comments first on UK founder threads.",
  ],
  trustParagraphs: [
    "Link building without trust on your own site wastes equity. Visitors who click through must land on a credible offer.",
    "Google rewards helpful content and natural citations. Manipulative schemes stall growth and can trigger manual actions.",
    "A public review profile gives partners neutral language to link to—especially useful when you are not yet famous enough for press coverage.",
    "Partners link more willingly when you offer a neutral page describing your product—they avoid feeling like paid promoters.",
    "Journalists prefer citeable profiles over marketing homepages when fact-checking founder claims.",
    "Referral traffic from citations behaves like warm outreach—proof on the landing page determines whether the link was worth earning.",
  ],
  playbookParagraphs: [
    "Publish data or benchmarks only you can produce—even small surveys of UK founders in your niche count.",
    "Guest post on newsletters and blogs where your buyers already read. Lead with insight, mention your product softly.",
    "Build free tools: calculators, templates, checklists. Tools earn links because they are genuinely useful.",
    "HARO and journalist request services still work when responses are specific and fast.",
    "Partner with accelerators, coworking spaces and local startup groups for resource pages listing members.",
    "Create comparison content that helps buyers decide ethically—avoid trashing competitors unfairly.",
    "Fix broken link opportunities using SEO tools: find dead links on relevant sites and suggest your resource.",
    "Sponsor niche events for brand mentions when budget allows—choose events your ICP attends.",
    "Contribute to open source or documentation ecosystems related to your product category.",
    "Pitch podcast appearances with a clear story arc and a profile link hosts can drop in show notes.",
    "List on high-quality directories sparingly—prefer those with editorial standards.",
    "Publish a Review Signal profile and reference it in outreach as a neutral third-party page about your product.",
    "Maintain a spreadsheet of journalists and newsletter authors who covered adjacent tools—polite follow-ups after launches work.",
    "Offer expert comments on UK startup trends to local business press—one quote can earn a durable link.",
    "Refresh cornerstone guides yearly; updated dates encourage partners to relink.",
    "Share data visualisations on social with embed codes—visual assets attract links naturally.",
    "Reference your review profile in guest author bios as the neutral page about your product.",
    "Keep a running list of URLs that already link to you—thank authors when you ship updates they can mention again.",
    "When outreach fails, improve the asset: add data, refresh the title, or link to your editorial profile for credibility.",
    "Track referral sessions from your review profile separately so you know when citations drive humans, not only SEO tools.",
    "Quarterly, merge duplicate blog posts and redirect weak pages so link equity consolidates on your best resources.",
    "Lead community threads with insight first; drop your profile link only when someone asks what you built.",
    "Publish original charts or benchmarks UK founders cannot find elsewhere—visual assets earn links without aggressive outreach.",
    "When a journalist cites you, save the URL and update your press page—future partners trust visible track records.",
    "Comment on two UK founder threads with genuine advice before mentioning your tool—relationships precede links.",
    "Ship a changelog post worth linking whenever you release a meaningful feature—not only launch-day announcements.",
    "Offer to co-author a guest piece with a complementary founder—both sites gain a relevant link and shared audience.",
    "Track brand mentions in Google Alerts and ask politely for a link when someone references you without one.",
  ],
  sellParagraphs: [
    "Review Signal adds a linkable asset to your stack: a live profile page, directory listing potential and a backlink to your domain from the review record.",
    "Use the profile URL in press kits, launch posts and partner emails—give people something credible to reference.",
    "Starter (£99) and Enhanced (£199) packages include publication of your profile and outbound link when accepted.",
    "Preview /example-review when writing author bios so partners know what they are linking to.",
  ],
  convertParagraphs: [
    "Backlinks send humans as well as bots. Landing pages must convert that referral traffic with proof above the fold.",
    "When someone links to your review profile, readers should find a clear path to your website from that page.",
    "Browse published apps in the directory to see how reviewed products present citations and outbound links.",
    "Track referral landing pages in analytics—if backlink traffic bounces, add the editorial quote to that URL before pitching more links.",
    "Press kits should list the profile URL first and the homepage second—reporters link to pages they can cite without sounding promotional.",
  ],
  credibleParagraphs: [
    "Not all links are equal. Profile pages from review programmes should be disclosed appropriately; Review Signal profiles are editorial records with clear context.",
    "Pair link building with on-site trust so referral visitors sign up instead of bouncing.",
    "Guidelines explain our review approach for partners who ask about editorial standards.",
    "When pitching guest posts, offer the profile as the author bio link—editors accept neutral citations more often than product homepages.",
    "If a partner asks whether your review is paid placement, point them to the methodology page and review ID—transparency protects the link long term.",
  ],
  sellBullets: [
    "Indexable editorial profile URL for citations",
    "Outbound link from review record to your site",
    "Directory listing when suitable for discovery",
    "Review ID for journalists and partners to reference",
    "Editorial summary others can quote with context",
    "Badge asset for co-marketing and resource pages",
  ],
  placementParagraphs: [
    "Promote linkable assets wherever you pitch stories or partnerships.",
    "Add the profile URL to your media kit above social links—reporters grab the first credible URL they see.",
    "When a partner links to your profile, ensure your site’s hero shows matching proof so referral visitors convert.",
  ],
  placementBullets: [
    "Press kit: profile URL + quote",
    "Guest author bio",
    "Podcast show notes",
    "Partner resource pages",
    "Launch threads with profile link",
    "Investor updates footers",
  ],
  comparisonParagraphs: [
    "Buying link packages or spamming directories builds numbers that search engines ignore—and referral visitors still bounce on anonymous homepages.",
    "Review Signal gives you an editorial page partners can cite ethically, plus a backlink to your site, so link building supports trust as well as rankings.",
    "A homepage pitch asks partners to trust your copy; a profile gives them a neutral page they can link without feeling promotional.",
  ],
  fastWinsParagraphs: [
    "Publish one citeable asset this month—a short UK founder survey or template—and pitch three relevant blogs with the profile in your bio.",
    "Add your profile URL to your press kit and podcast one-sheet before the next outreach batch.",
    "Fix one broken-link opportunity on a relevant UK startup resource page and suggest your citeable asset plus profile.",
    "Save three journalist emails from your niche and send one helpful comment this week—no pitch attached, only genuine insight.",
  ],
  nextStepsParagraphs: [
    "Apply at /submit when your site and offer are clear, compare Starter (£99) and Enhanced (£199) on /pricing, and note how /example-review presents citeable copy.",
    "After publication, pitch one newsletter with the profile link and improve the landing page that receives referral traffic with quote and badge.",
    "Monthly, export referring domains and thank authors when you ship updates—they often link again.",
    "List your profile on your About page press section so partners always find a neutral citation target.",
  ],
  winsBullets: [
    "Publish one linkable resource",
    "Pitch three relevant blogs",
    "Fix one broken link opportunity",
    "Add profile URL to press kit",
    "Submit to one quality directory",
    "Apply for Review Signal profile",
    "Track referring domains monthly",
    "Improve landing proof for referral traffic",
  ],
  faq: [
    {
      q: "How do startups get backlinks in the UK?",
      a: "Create citeable assets, guest contribute, earn tool links and reference neutral review profiles. Avoid paid link schemes. Focus on relevance and editorial quality.",
    },
    {
      q: "Does Review Signal provide a backlink?",
      a: "Published profiles include a link from your review record to your website, plus a public profile URL others can reference. Directory listing adds another discovery path.",
    },
    {
      q: "Are directory links still useful?",
      a: "Selective, editorial directories can help discovery. Avoid spam lists. Review Signal directory focuses on reviewed products—not bulk submissions.",
    },
    {
      q: "Should I buy backlinks?",
      a: "Buying links violates search guidelines and risks penalties. Invest in assets and relationships that earn natural citations.",
    },
    {
      q: "What anchor text should partners use?",
      a: "Natural brand and product names work best. Over-optimised anchor text looks manipulative. Let partners describe you honestly.",
    },
    {
      q: "When is a review profile worth citing?",
      a: "After publication—use it in launches, comparisons and outreach when you need a third-party page about your product.",
    },
    {
      q: "How much does a profile cost?",
      a: "From £99 Starter to £199 Enhanced for manual review and published assets.",
    },
    {
      q: "Can I link to my profile from my own site?",
      a: "Yes—badge and text links from your site to the profile reinforce trust. The profile also links back to you.",
    },
  ],
});
