import { buildGuideBody } from "@/content/seo/build-guide";
import type { SeoGuideContent } from "@/lib/seo-types";

export const howToConvinceVisitorsBeforeTheyBuyContent: SeoGuideContent = buildGuideBody({
  valueBenefits: [
    {
      title: "Pre-purchase proof",
      outcome: "Answer doubt before checkout.",
      detail:
        "Visitors open your review profile while still on your site—then return ready to buy.",
      accent: "#3B82F6",
    },
    {
      title: "Forwardable record",
      outcome: "Help champions sell internally.",
      detail:
        "Send a review ID to stakeholders who were not on your demo call.",
      accent: "#D4A943",
    },
    {
      title: "Quote near CTA",
      outcome: "Reinforce the final click.",
      detail:
        "Editorial language beside “Buy now” or “Start trial” reduces last-minute hesitation.",
      accent: "#22C55E",
    },
  ],
  winningParagraphs: [
    "Pre-purchase conviction is the moment a visitor believes your product will deliver enough value to pay. Winning means removing doubt in the final meters of the journey—not only at awareness.",
    "Map hesitation: price, risk, implementation, alternatives, trust. Address each on the pages that precede payment.",
    "Buyers who feel informed convert with less discounting and support overhead.",
    "Map the buying committee: user, manager, finance, legal—and place proof where each role looks.",
    "Offer a one-page security or compliance summary if enterprise buyers stall late in the funnel.",
    "Measure pre-purchase success by checkout completion and sales-cycle length—not top-of-funnel traffic alone.",
    "The last click before payment is a trust click—treat checkout proof as part of the product experience.",
  ],
  trustParagraphs: [
    "Visitors often leave to search your brand. What they find elsewhere should match what you claim—ideally including an independent review they can read.",
    "UK buyers appreciate directness. Overpromising triggers backlash; clear proof triggers progress.",
    "Convincing visitors is empathy: show you understand their job-to-be-done and the risks they fear.",
    "Hesitation is often information asymmetry—you know the product; they do not. Proof closes the gap.",
    "High-ticket purchases benefit from layered proof: quote near CTA, profile link in FAQ, review ID in sales email.",
    "Trials that hide renewal terms until checkout train buyers to distrust you—pair transparent billing with external proof.",
  ],
  playbookParagraphs: [
    "List every pre-purchase question from sales calls and support tickets. Turn answers into FAQ entries on pricing pages.",
    "Show total cost of ownership simply: subscription, seats, implementation time, what is included.",
    "Offer a reversible first step—trial, demo or money-back window—when your economics allow it.",
    "Compare honestly to alternatives including doing nothing. Buyers respect nuance.",
    "Use screenshots of outcomes, not only features. Show the after state.",
    "Display security, privacy and data handling information where B2B buyers expect it.",
    "Add live chat or clear support hours for high-ticket offers—silence feels like abandonment.",
    "Include refund or cancellation policy in plain English.",
    "Show who you serve with specific personas: “for UK accountancy practices” beats “for everyone”.",
    "Retarget abandoners with proof-forward messaging, not only discounts.",
    "Place Review Signal badge and quote on checkout and pricing so last-click anxiety meets verification.",
    "Link champions to the public profile during sales cycles so internal approvers self-serve trust.",
    "Add short video walkthroughs on pricing pages for products that need seeing to be believed.",
    "Publish integration or security one-pagers PDFs sales can attach—reduces repetitive questions.",
    "Use exit-intent offers only when they reinforce value, not desperation discounts.",
    "Mirror language from sales calls in FAQ headings—buyers recognise their own words.",
    "Send profile links after demos with a one-line summary of what was reviewed—reinforces the call.",
    "Block time monthly to sharpen one pre-purchase page: headline, objection FAQ, and a refreshed Review Signal quote that matches the live product.",
    "When you share wins on LinkedIn or in newsletters, link your profile so curious readers verify claims without booking a call.",
    "Log which objections appear in lost-deal notes and mirror that language in pricing FAQ—buyers recognise their own words.",
    "After major releases, confirm checkout and pricing still match what the editorial profile describes.",
    "Keep a short list of pages that drive demo requests and ensure each shows proof above the fold on mobile.",
    "Train support to paste the profile URL when tickets ask “can I trust this vendor?”—consistent answers build brand reliability.",
    "Create a one-page security or compliance PDF for enterprise buyers and link it beside your profile on pricing.",
    "Mirror top three sales-call objections as FAQ H2s on the pricing page—buyers scan headings before they read body copy.",
    "Offer a calculator or estimator on pricing when ROI is hard to imagine—numbers reduce abstract fear.",
    "Show implementation timeline with named milestones so buyers know what week one looks like after purchase.",
    "Publish integration logos only with permission and link each to a short explanation of what data flows where.",
    "Add a “what happens after purchase” timeline on pricing—uncertainty about onboarding blocks more deals than price.",
    "Offer office hours for enterprise trials—human access reduces fear when contracts are large.",
  ],
  sellParagraphs: [
    "Review Signal helps you convince visitors before they buy with a verifiable editorial profile, publishable quote and badge tied to a full public record.",
    "Enhanced profiles (£199) articulate strengths and limitations—useful when buyers compare nuanced SaaS tools.",
    "Starter (£99) delivers fast credibility for straightforward offers.",
    "Review /example-review before checkout tests so quote placement matches how UK buyers read on phones.",
  ],
  convertParagraphs: [
    "Conviction is visual and textual. Pair product proof with third-party editorial proof on the same screen.",
    "Use the publishable quote as the voice of reason beside your CTA button.",
    "Walk through the example profile to see how reviewed signals answer pre-purchase questions efficiently.",
    "On checkout, show the refund policy and the review badge in the same viewport—risk reduction works in pairs.",
    "If cart abandonment emails only offer discounts, test a version with the profile link and a single objection answered.",
  ],
  credibleParagraphs: [
    "Testimonials without context feel selectable. Editorial reviews with review IDs feel inspectable.",
    "Combine customer stories with Review Signal summaries for emotional and structural proof.",
    "Guidelines document review methodology for buyers who ask “who checked this?”",
    "Procurement teams bookmark neutral profiles—make sure yours opens quickly on mobile and states what was reviewed.",
    "Enhanced profiles that list limitations can increase trust on considered purchases because buyers see honesty.",
    "Sales teams should never paraphrase the editorial quote beyond recognition—link to the profile for full context.",
    "If legal reviews your site, include the review ID in the packet—external records speed internal sign-off.",
  ],
  sellBullets: [
    "Review ID for self-serve verification before purchase",
    "Publishable quote for pricing and checkout screens",
    "Badge linking to full editorial profile",
    "Summary framing offer fit and reviewed signals",
    "Profile URL for demo follow-up and proposals",
    "Backlink plus directory discovery when listed",
  ],
  placementParagraphs: [
    "Pre-purchase pages deserve the strongest proof on your site.",
    "Add the profile link to the top three FAQ entries on pricing—those are the questions that block the buy button.",
    "In proposal PDFs, place the review ID on the cover page so approvers verify before reading feature lists.",
    "On comparison pages, show the editorial quote beside your primary CTA so hesitant visitors see verification at the decision point.",
  ],
  placementBullets: [
    "Pricing tables",
    "Checkout and cart",
    "Comparison pages",
    "Demo follow-up emails",
    "Proposal appendices",
    "FAQ accordion top entries",
  ],
  comparisonParagraphs: [
    "Many funnels rely on urgency and discounts at checkout—yet abandonment stays high because buyers still cannot verify the vendor independently.",
    "Review Signal adds a neutral profile with review ID and editorial summary, so pre-purchase visitors validate claims before they enter payment details.",
    "Self-selected testimonials alone rarely satisfy procurement; an editorial record gives approvers language they did not hear on your sales call.",
    "Discounts buy time; proof buys confidence—use both sparingly and measure which reduces sales-cycle length for your ICP.",
  ],
  fastWinsParagraphs: [
    "Document your top five pre-buy objections from sales this week and add FAQ answers plus the profile link on the pricing page.",
    "Add the publishable quote beside the primary checkout CTA before running another retargeting campaign.",
    "Send one open opportunity the profile URL today instead of another feature PDF—measure reply rate and stage movement.",
  ],
  nextStepsParagraphs: [
    "Apply at /submit with pricing and policies visible on your live site, compare Starter (£99) and Enhanced (£199) on /pricing, and review /example-review for checkout-adjacent placement.",
    "After publication, send the profile URL in every demo follow-up and cart-abandonment sequence for the next month.",
    "Add the review ID to your proposal cover page template so every new opportunity starts with verification.",
    "Review checkout abandonment reasons in analytics and add one FAQ answer tied to the top exit page.",
    "Share the profile with your sales team in Slack and ask them to log when prospects mention the review ID on sales calls.",
  ],
  winsBullets: [
    "Document top five pre-buy objections",
    "Expand pricing FAQ",
    "Add quote to checkout",
    "Send profile link in proposals",
    "Record one customer outcome video",
    "Clarify refund policy",
    "Apply for Review Signal",
    "Review abandonment analytics",
  ],
  faq: [
    {
      q: "How do I convince website visitors to buy?",
      a: "Answer objections on pricing pages, show real outcomes, offer a low-risk first step and add verifiable third-party proof. Make it easy to confirm you are legitimate before payment.",
    },
    {
      q: "What reduces buyer hesitation online?",
      a: "Transparent pricing, clear policies, product evidence and independent review profiles visitors can open in a new tab.",
    },
    {
      q: "Should proof be on checkout pages?",
      a: "Yes—last-step hesitation is common. A badge linking to an editorial profile helps visitors complete purchase.",
    },
    {
      q: "Can B2B buyers use Review Signal internally?",
      a: "Champions forward the profile URL and review ID to finance, legal or leadership—speeding internal approval.",
    },
    {
      q: "What if my product is complex?",
      a: "Choose Enhanced for deeper editorial treatment including strengths and limitations buyers expect for considered purchases.",
    },
    {
      q: "How do quotes work on sales pages?",
      a: "Use the publishable editorial quote with attribution and a link to the full profile for context.",
    },
    {
      q: "Pricing for review profiles?",
      a: "£99 Starter and £199 Enhanced cover manual review and publication if suitable.",
    },
    {
      q: "Does proof replace a demo?",
      a: "For some products, yes—for others, proof plus demo wins. Profiles support both self-serve and sales-led motions.",
    },
  ],
});
