import { buildGuideBody } from "@/content/seo/build-guide";
import type { SeoGuideContent } from "@/lib/seo-types";

export const socialProofWithoutFakeReviewsContent: SeoGuideContent = buildGuideBody({
  valueBenefits: [
    {
      title: "Verifiable record",
      outcome: "Replace anonymous star clutter.",
      detail:
        "Review ID and public profile give skeptics something real to open—not fabricated ratings.",
      accent: "#3B82F6",
    },
    {
      title: "Editorial integrity",
      outcome: "Show you chose transparency.",
      detail:
        "Manual review process with clear context signals maturity to UK buyers.",
      accent: "#D4A943",
    },
    {
      title: "Quote with context",
      outcome: "Publish proof that sounds human.",
      detail:
        "Use the editorial line on your site with attribution visitors can verify.",
      accent: "#22C55E",
    },
  ],
  winningParagraphs: [
    "Social proof should help visitors decide—not manipulate them. Winning means assembling evidence that survives scrutiny: real customers, real data and verifiable third-party records.",
    "Fake reviews are a short-term crutch with long-term brand damage. UK regulators and platforms increasingly penalise misleading practices.",
    "Build a proof stack you are proud to defend in sales calls, press interviews and due diligence.",
    "Document your proof policy internally so marketing, sales and support never overclaim.",
    "When you earn press, link coverage to your review profile in follow-up emails to investors and customers.",
    "Ethical proof is a moat—competitors can copy features faster than they can copy your verified editorial record.",
  ],
  trustParagraphs: [
    "Sophisticated visitors spot generic testimonials, stock faces and review patterns that look purchased.",
    "Ethical social proof accelerates growth because it aligns marketing with product reality—fewer refunds, happier customers.",
    "Founders who invest in editorial verification signal they are building for the long term, not a quick flip.",
    "Regulators and platforms aside, your reputation with customers is the ultimate trust metric—honest proof protects it.",
    "Verifiable editorial records age well; inflated star campaigns do not.",
    "Your support team hears truth about the product every day—let honest proof on the site reflect that same reality for new visitors.",
  ],
  playbookParagraphs: [
    "Collect testimonials with full name, role and permission. Specific outcomes beat vague praise.",
    "Never post reviews you cannot substantiate. If you would not share it in a board meeting, do not publish it.",
    "Disclose incentives when you run referral or review campaigns. Transparency is a feature.",
    "Use video testimonials sparingly but powerfully—short, authentic clips outperform polished fakery.",
    "Show metrics only when accurate: user counts, uptime, customer logos with contracts.",
    "Publish case studies with methodology: problem, approach, outcome, timeframe.",
    "Avoid aggregating ratings from incompatible sources on your homepage—it confuses more than convinces.",
    "Moderate UGC communities on your brand responsibly; toxic spaces erode trust.",
    "Train support to ask for feedback after resolved tickets—organic voice beats scripted praise.",
    "Link privacy and data practices clearly when you display user content.",
    "Add a Review Signal editorial profile as external verification—prospects see an independent record with review ID.",
    "Combine customer voices with editorial summary so your proof page tells a complete story.",
    "Rotate proof quarterly on the homepage so returning visitors see momentum, not stale 2023 quotes.",
    "Label case studies with industry, company size and outcome metric—specificity reads as honest.",
    "Train sales to send the review profile before sending a deck—verification first, pitch second.",
    "Archive outdated testimonials that no longer match the product—stale proof hurts more than none.",
    "Celebrate customer wins in public posts with permission—authenticity attracts more proof over time.",
    "Run a quarterly proof audit: remove stale quotes, update metrics, and refresh the editorial badge if the product changed.",
    "When investors or enterprise buyers diligence you, send the review profile before the data room—verification sets the tone.",
    "Train every customer-facing role on what you can and cannot claim about reviews and ratings.",
    "Link press coverage to your profile in follow-up emails so third-party mentions connect to a single verifiable record.",
    "Prefer one strong editorial profile over five weak star widgets on the homepage—clarity beats clutter.",
    "Document incentive disclosure on referral campaigns so future marketing stays ASA-aligned.",
    "When a customer agrees to a case study, link to your editorial profile in the PDF footer—readers see both story and verification.",
    "Avoid importing star ratings from unrelated products or regions—mixed signals read as manipulation to careful buyers.",
    "Store signed testimonial permissions in your CRM so future marketers know what they may publish.",
    "When metrics change, update the site the same week—stale numbers are a form of misleading proof.",
    "Require legal review only for claims you cannot verify—speed matters, but accuracy matters more.",
    "Host customer quotes with full names when possible; initials-only praise reads as fabricated to skeptical UK B2B buyers evaluating new vendors.",
  ],
  sellParagraphs: [
    "Review Signal gives you social proof you can defend: a public profile, editorial quote, verification badge and review ID—without fake star inflation.",
    "Show prospects you chose verification over vanity metrics. Starter from £99; Enhanced £199 for richer editorial coverage.",
    "Deploy across homepage, pricing and sales collateral in one afternoon after publication.",
    "Read /guidelines with your team so everyone describes the editorial process consistently in sales calls.",
  ],
  convertParagraphs: [
    "Ethical proof converts better over time because it attracts buyers who will actually succeed with your product.",
    "Place verifiable proof beside CTAs: badge, quote and link to the full profile.",
    "Inspect the example profile to see how transparent review context should read.",
    "On comparison pages, show customer quotes and the editorial profile side by side—buyers should see both human and verified proof.",
    "If a testimonial lacks permission for name and role, do not publish it—use the editorial quote instead until you have proper consent.",
  ],
  credibleParagraphs: [
    "Third-party editorial reviews are not a replacement for customers—they are a complement that answers “who checked this product?”",
    "Review Signal profiles document reviewed signals and provide publishable quotes with clear attribution.",
    "Read guidelines to understand manual review steps and suitability checks.",
    "ASA-aligned UK marketing means accurate, verifiable claims—your proof stack should survive a skeptical lawyer’s skim.",
    "When investors diligence your startup, lead them to the review ID page before the pitch deck—verification sets the tone.",
  ],
  sellBullets: [
    "Defensible editorial record with public review ID",
    "Attributed publishable quote for marketing surfaces",
    "Badge linking to full review methodology",
    "Reviewed signals checklist visitors can verify",
    "Profile backlink plus optional directory listing",
    "Assets sales can send before the pitch deck",
  ],
  placementParagraphs: [
    "Ethical proof belongs on a dedicated section and at decision points—not hidden in legal footers.",
    "Build a “Proof” page that lists what each asset proves—customer quote, metric, editorial profile—and link out for verification.",
    "Quarterly, audit the homepage for stale logos or quotes that no longer match the product you ship today.",
    "Add the review ID to your sales one-pager footer so enterprise buyers can verify claims before scheduling legal review.",
  ],
  placementBullets: [
    "“Proof” or “Why trust us” section",
    "Homepage hero stack",
    "Pricing sidebar",
    "Investor data room index",
    "Sales deck proof slide",
    "Comparison pages vs alternatives",
  ],
  comparisonParagraphs: [
    "Fake or bought reviews inflate numbers until a buyer searches for context—then your brand looks worse than if you had shown less proof.",
    "Review Signal gives ethical social proof: a manual editorial record with review ID, so you can publish confidence without star inflation.",
    "Aggregated star widgets without context fail due diligence; a profile explains what was reviewed and links to methodology.",
    "Honest proof takes longer to assemble than buying stars—but it survives sales calls, press questions, investor diligence and customer referrals over years.",
  ],
  fastWinsParagraphs: [
    "Audit every homepage testimonial for name, role and permission—remove anything you cannot defend in a sales call.",
    "Add your editorial badge and profile link to the proof section before the next investor or enterprise sales cycle.",
    "Write a one-page internal proof policy this week so sales, marketing and support never overclaim.",
    "Remove one unverifiable metric or logo from the homepage today—even small honesty signals matter for cautious first-time UK visitors.",
  ],
  nextStepsParagraphs: [
    "Apply at /submit with accurate public claims on your site, compare Starter (£99) and Enhanced (£199) on /pricing, and read /guidelines on editorial standards.",
    "After publication, rebuild your proof page with customer quotes plus the profile link—and remove any unverifiable star widgets.",
    "Share the profile in your next board or investor update so stakeholders see you chose verifiable proof over vanity metrics.",
    "Train new hires on the proof page during onboarding—consistent language prevents accidental overclaim in outbound email.",
    "Publish your proof policy on the public site so visitors see you take verification seriously—not only your marketing, sales, and customer support teams internally.",
  ],
  winsBullets: [
    "Audit testimonials for permission",
    "Remove unverifiable claims",
    "Publish two case studies",
    "Add disclosure where incentives exist",
    "Apply for Review Signal profile",
    "Place badge on homepage",
    "Link profile in sales emails",
    "Quarterly proof stack review",
  ],
  faq: [
    {
      q: "How do I get social proof without fake reviews?",
      a: "Use permission-based testimonials, real metrics, case studies and an independent editorial review profile visitors can verify. Avoid purchased or bot-generated ratings.",
    },
    {
      q: "Are five-star widgets enough?",
      a: "They help inside platforms but rarely convince on your own site. Add verifiable editorial profiles and named customer stories.",
    },
    {
      q: "What is verifiable social proof?",
      a: "Evidence a visitor can check: named customers, public data and third-party review records with review IDs and profile URLs.",
    },
    {
      q: "How does Review Signal avoid fake review culture?",
      a: "We publish editorial profiles based on manual review of your live product—with clear context—not bulk star ratings for sale.",
    },
    {
      q: "Can I edit my editorial review?",
      a: "Profiles reflect what was reviewed. Contact support for factual corrections; marketing spin is not substituted for assessment.",
    },
    {
      q: "What should I show on a proof page?",
      a: "Customer quotes, metrics, case studies, Review Signal badge and link to full profile, plus policies and contact details.",
    },
    {
      q: "UK rules on testimonials?",
      a: "Avoid misleading claims and disclose material connections. Ethical proof practices align with ASA principles—be accurate and verifiable.",
    },
    {
      q: "Cost of a review profile?",
      a: "Starter £99 and Enhanced £199 for manual review and published assets when suitable and accepted.",
    },
  ],
});
